language: julia
os:
  - linux
  - osx
julia:
  - 0.6
matrix:
  allow_failures:
    - os: osx
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("IPC"); Pkg.test("IPC"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("IPC")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("IPC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
