language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
matrix:
  allow_failures:
    - os: osx
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'if VERSION >= v"0.7.0-DEV.5183"; using Pkg; end; Pkg.clone(pwd()); Pkg.build("IPC"); Pkg.test("IPC"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'if VERSION >= v"0.7.0-DEV.5183"; using Pkg; end; cd(Pkg.dir("IPC")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'if VERSION >= v"0.7.0-DEV.5183"; using Pkg; end; cd(Pkg.dir("IPC")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.build("IPC"); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
